### PR TITLE
fix!: upgrade nitropack

### LINKED ISSUE #31: bridge run `generate`, no dist directory generated
### Environment

Nuxt project info:                                                                                                                                                                                                    09:55:03

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.18`
- Builder:          `webpack`
- User Config:      `build`, `bridge`, `target`, `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `publicRuntimeConfig`, `loading`
- Runtime Modules:  `@pinia/nuxt@0.1.8`
- Build Modules:    `@vueuse/nuxt@8.2.5`, `8n`, `@nuxt/bridge@3.0.0-27491748.3186841`
------------------------------

### Reproduction
link: https://codesandbox.io/s/qvijbf?file=/nuxt.config.js
config :
```
defineNuxtConfig({
  target: 'static',
  bridge: {
    nitro: process.env.NODE_ENV !== 'production'
  },
})
```

`nuxi generate`

### Describe the bug

no `dist` dir

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #32: `nuxi generate` does not create `.output` directory anymore
### Environment

- Nuxt version: `2.16.0-27358576.777a4b7f`
- @nuxt/bridge version: `3.0.0-27495976.e31c604`
- nitropack version: `0.2.5`

### Reproduction

As the linked, simple renovate-PR highlights the issue, I don't think another repro is needed. If it is, feel free to tell me.

### Describe the bug

After upgrading `@nuxt/bridge` I receive the [error](https://github.com/dargmuesli/jonas-thelemann/runs/5992266520?check_suite_focus=true#step:5:199) `FATAL  [nitro] Please use nuxt generate for static target`, which I (kinda) already do (`nuxi generate`).
Later on in the same build I now receive a webpack [error](https://github.com/dargmuesli/jonas-thelemann/runs/5992266520?check_suite_focus=true#step:5:247) originating from `@nuxt/bridge`, which I can "fix" by adding `@nuxt/bridge` to the `build.transpile` array.
After doing so tough, **there is no `.output` directory created anymore**.

### Additional context

Sounds similar to https://github.com/nuxt/framework/issues/4179.

### Logs

```shell
https://github.com/dargmuesli/jonas-thelemann/runs/5992266520
```

### LINKED ISSUE #322: nuxt-bridge nitro preset 'aws-lambda' fails to launch
### Environment

This seems to be the case in multiple environments, including the code sandbox template:

Code Sandbox: 
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Builder:          `webpack`
- User Config:      `nitro`, `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27498038.f18e68b`

macOS:
------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.3.0`
- Builder:          `webpack`
- User Config:      `ssr`, `nitro`, `target`, `head`, `publicRuntimeConfig`, `css`, `styleResources`, `plugins`, `components`, `buildModules`, `modules`, `build`, `bridge`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/style-resources@1.2.1`, `@nuxt/bridge@3.0.0-27498038.f18e68b`

### Reproduction

https://codesandbox.io/s/nuxt-bridge-aws-lambda-preset-8r065h

### Describe the bug

When starting the Nuxt Bridge dev server, the following error occurs:

```
 ERROR  [worker reload] [worker] exited                               15:39:42

  at Worker.<anonymous> (node_modules/nitropack/dist/chunks/prerender.mjs:2039:14)
  at Object.onceWrapper (events.js:520:26)
  at Worker.emit (events.js:400:28)
  at Worker.emit (domain.js:475:12)
  at Worker.[kOnExit] (internal/worker.js:278:10)
  at Worker.<computed>.onexit (internal/worker.js:203:20)

```
In the browser, a **503 error** code is given showing the same error from the terminal

### Additional context

This appears to affect Nuxt Bridge only. Nuxt 3 launches without errors using the aws-lambda nitro preset

### Logs

_No response_

### LINKED ISSUE #375: addRouteMiddleware is not working in production mode
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.0-27606262.123206cb`
- Package Manager:  `npm@7.24.1`
- Builder:          `webpack`
- User Config:      `modules`, `bridge`, `buildModules`
- Runtime Modules:  `~/modules/middleware-module`
- Build Modules:    `@nuxt/bridge@3.0.0-27566698.2b0045e`
------------------------------

### Reproduction

https://github.com/AndreyYolkin/reproduction/tree/globalMiddleware

### Describe the bug

When we try to dynamically insert global route middleware it causes error after running production build. In dev mode everything is ok

### Additional context

[Error probably locates in this string](https://github.com/nuxt/bridge/blob/2b0045e084956e6eee9e6b2b0c5c6c3be93b3794/src/runtime/composables.ts#L240)
after building for production `nuxtApp._middleware.global.push` turns into `nuxtApp._middleware.globalThis.push`

I tried to revert this replacement back to 'global' and build became working again

### Logs

```shell
[nuxt] [request error] Cannot read properties of undefined (reading 'push')
  at addRouteMiddleware (/C:/Projects/reproduction/.output/server/chunks/server.mjs:6816:40)
  at /C:/Projects/reproduction/.output/server/chunks/server.mjs:8519:27
  at callWithNuxt (/C:/Projects/reproduction/.output/server/chunks/server.mjs:6828:24)
  at /C:/Projects/reproduction/.output/server/chunks/server.mjs:6836:30
  at createApp (/C:/Projects/reproduction/.output/server/chunks/server.mjs:8676:15)
  at async __webpack_exports__.default (/C:/Projects/reproduction/.output/server/chunks/server.mjs:8777:11)
  at async renderToString (/C:/Projects/reproduction/.output/server/chunks/renderer.mjs:280:19)
  at async /C:/Projects/reproduction/.output/server/chunks/renderer.mjs:613:20
  at async /C:/Projects/reproduction/.output/server/node_modules/h3/dist/index.mjs:420:19
  at async Server.nodeHandler (/C:/Projects/reproduction/.output/server/node_modules/h3/dist/index.mjs:370:7)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #322, resolves #31, resolves #32, resolves #375, resolves https://github.com/nuxt/bridge/issues/356

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This upgrades nitropack which should fix a few issues on the books at the moment. ~~Also note https://github.com/nuxt/bridge/pull/316 which could be combined with this one.~~

**Breaking change**: `nuxi generate` now behaves differently using nitro prerendering instead of the Nuxt 2 full-static approach. If you would like to keep the Nuxt 2 generation logic while still using `nitro`, you can run `nuxi generate --classic` or set `bridge.nitroGenerator`.

**Progress**:
- [x] upgrade nitropack
- [x] native `nuxi generate` prerendering - ssr & spa
- [x] fix nuxt 2 SSG/static behaviour (currently broken - renders pages with 503 unavailable)

### 👉 Migration

If you were relying on the previous full static generation of Nuxt, you should switch to using `nuxt generate` rather than `nuxi generate`, and, if necessary, specify the executable more specifically, such as with:

```json
{
  "scripts": {
    "build": "./node_modules/nuxt/bin/nuxt.js generate"
  }
}
```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Luferov** [comment]
@pi0, what about this PR? If you accept it, it will be great, please! 🙏❤️

**Comment by dargmuesli** [comment]
Hey @danielroe, can we help somehow to get this done?
I know about the priority on nuxt/framework, but this is really **the** major issue with bridge right now, sadly. Having a P4 resolved would allow for a much better experience.
Could we maybe have a little chat besides that exact issue on Discord because @pi0 is currently busy with other things? Feel free to tell me what fits for you!

**Comment by pi0** [comment]
@danielroe is the current maintainer of this repo :) There is no need for my approval 👍🏼

**Comment by Luferov** [comment]
What about https://github.com/nuxt/bridge/issues/319. This PR may close #319 issue? I can't  upgrade nuxt-bridge :(

**Comment by dargmuesli** [comment]
@P4sca1 are you asking whether https://github.com/nuxt/bridge/issues/375 is fixed? I only checked for `.output` generation yet.

**Comment by P4sca1** [comment]
Alright, I will check the other 2 issues I currently have after the PR has been merged.

**Comment by dargmuesli** [comment]
In case anyone else wants to test this fix too for their project, here are the steps to do so in your project:
1. clone the bridge repo
2. checkout the `fix/nitropack` branch
3. run `yarn install`, `yarn build` and `yarn pack`
4. in your project, replace the bridge import with `"@nuxt/bridge": "file:...../nuxt-bridge/nuxt-bridge-v3.0.0.tgz",`
5. build your project
6. check the results!

I'd be fine with a soon merge of this PR of course. I can't imagine it breaking more than what already broke? 🤭

**Comment by dargmuesli** [comment]
@danielroe you write 
> If you were relying on the previous full static generation of Nuxt, you should switch to using nuxt generate rather than nuxi generate...

Would you mind explaining the reason why that is recommended? I suppose `nuxi` is missing static rendering capabilities?

**Comment by MartinX3** [comment]
@dargmuesli 
> 4\. "@nuxt/bridge": "file:...../nuxt-bridge/nuxt-bridge-v3.0.0.tgz"

I tried
`"@nuxt/bridge": "/home/developer/bridge/nuxt-bridge-v3.0.0.tgz"`
and
`"@nuxt/bridge": "file:/home/developer/bridge/nuxt-bridge-v3.0.0.tgz"`
both resulting in `/tmp/build-1657186514315.sh: Zeile 2: nuxi: Kommando nicht gefunden.`

**Comment by MartinX3** [comment]
@dargmuesli 
> 4\. "@nuxt/bridge": "file:...../nuxt-bridge/nuxt-bridge-v3.0.0.tgz"

I tried
`"@nuxt/bridge": "/home/developer/bridge/nuxt-bridge-v3.0.0.tgz"`s
and
`"@nuxt/bridge": "file:/home/developer/bridge/nuxt-bridge-v3.0.0.tgz"`
both resulting in `/tmp/build-1657186514315.sh: Zeile 2: nuxi: Kommando nicht gefunden.`

**Comment by dargmuesli** [comment]
I've experienced the file source to be a little buggy sometimes, and I don't know why that is. To be sure, you can also extract the `.tgz` to `node_modules/@nuxt/bridge` manually.

**Comment by dargmuesli** [comment]
> the error is now Uncaught SyntaxError: Invalid or unexpected token (at 5c5260d.js:2:76798)

Would be interesting to see the offending part of the file.
Just a hint: you've duplicated your last comment, you can delete one ;)

**Comment by MartinX3** [comment]
@dargmuesli 
thank you
I extracted it, still `nuxi` is an unknown command.
`nuxt generate` results into the same broken output.

Here is the file from the error `Uncaught SyntaxError: Invalid or unexpected token (at 5c5260d.js:2:76798)`:
[5c5260d.js.zip](https://github.com/nuxt/bridge/files/9062411/5c5260d.js.zip)

**Comment by MartinX3** [comment]
@dargmuesli 
thank you
I extracted it, still `nuxi` is an unknown command.
`nuxt generate` results into the same broken output.

Here is the file from the error `Uncaught SyntaxError: Invalid or unexpected token (at 5c5260d.js:2:76798)`:
[5c5260d.js.zip](https://github.com/nuxt/bridge/files/9062411/5c5260d.js.zip)

**Comment by dargmuesli** [comment]
Hmm, I don't see anything special about
```
,[s,y]=r.b.sincos(v);
            ^
```
...

You last comment got posted 3 times now ;D please find out why that's happening. We get notifications for every comment.

**Comment by MartinX3** [comment]
Argh, sorry.
Github is telling me all the times `you can't post at this time`.
Maybe the Microsoft Guys are doing some Updates in the back.
I'm sorry.

**Comment by dargmuesli** [comment]
Did you try using `nuxt generate` instead of `nuxi generate`? @danielroe said to do so in the first post, but I'm not entirely sure why yet.

**Comment by MartinX3** [comment]
@dargmuesli 
Yes, because `nuxi generate` either tells me `nuxi not found` with this PR or it won't give me an `.output` folder without this PR.

**Comment by P4sca1** [comment]
> * clone the bridge repo
> * checkout the `fix/nitropack` branch
> * run `yarn install`, `yarn build` and `yarn pack`
> * in your project, replace the bridge import with `"@nuxt/bridge": "file:...../nuxt-bridge/nuxt-bridge-v3.0.0.tgz",`
> * build your project
> * check the results!

This does not work for me either. 
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '[omitted]/node_modules/@nuxt/bridge/bin/nuxt.mjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I think the reason is that `yarn pack` does not pick up the `bin` folder, because it is not listed in `files` in `package.json`

**Comment by P4sca1** [comment]
`nuxi dev` seems to work fine. `nuxi build` ran for around 10 minutes and then crashed with heap out of memory. The log contains output like `ℹ Initializing prerenderer` and `ℹ Initializing prerenderer`. I intend to use server side rendering without any pre-rendering (deployment as a Node.js server). Is it intended that pre-rendering is performed with `ssr: true` in `nuxt.config.ts`? I have not changed the `nitro` configuration.

**Comment by MartinX3** [comment]
I can confirm that `nuxi generate` now works.

The hook from #27 is still needed for static generation without SSR.

The `.output/public/index.html` has the same issue I mentioned before:

```
e8733a2.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
0bc3695.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
2f420ae.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
527fe90.js:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
```

I replaced `src="/_nuxt/` with `src="_nuxt/`.
This results into `2f420ae.js:2 Uncaught SyntaxError: Invalid or unexpected token (at 2f420ae.js:2:76798)`

Thank you for fixing the obstacles towards the broken static site generation without ssr.

**Comment by danielroe** [comment]
It's likely there are remaining issues, but I think this PR is sufficient to enable us to test and iterate with edge releases.

Thank you to everyone who has tested it so far - please let me know in a new issue if you are experiencing any issues ❤️

**Comment by MartinX3** [comment]
> Hmm, I don't see anything special about

@dargmuesli 
I think the texteditor showed us the wrong position.
The browser console shows me the real position of the invalid character.
`v=t.d*n+t.m*o+t.n*l+t.f*c+t.Ï‰*d,[s,y]=r.b.sincos(v);`
at
`Ï‰`

**Pull request merged**
