### PR TITLE
fix: avoid using shared global state for head

### PR DESCRIPTION
**Pull request by wattanx**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
If you use UnheadPlugin, you need to add unhead to $options.
If useHead is used without being added, a vue warn will be thrown.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by harlan-zw** [comment]
Thanks for updating it, though in what context is this thrown?

> UnheadPlugin from @unhead/vue causes [Vue warn]: injection "usehead" not found., so fixed for Nuxt 2.

There's probably a better fix than copying over the plugin code.

**Comment by wattanx** [comment]
@harlan-zw 
Thanks ❤️ 

If you use `UnheadPlugin`, you need to add `unhead` to $options.
If `useHead` is used without being added, a `vue warn` will be thrown.

https://github.com/unjs/unhead/blob/53e63ca42d8311e9690513aab8f6cff0d067b2df/packages/vue/src/vue2/index.ts#L39-L53

I tried to think of a way to add `unhead` to `$options` in the case of Nuxt, but couldn't come up with a good way.

**Comment by harlan-zw** [comment]
Hi @wattanx, sorry I couldn't get this code pushed up for your talk!

I've pushed up some changes that fix the warnings being emitted which I think is the underlying issue you may have been trying to solve? For now I think Nuxt 2 should use the deprecated plugin as the new one has some issues, I'll either need to fix the new plugin or bridge can stay on the deprecated version (for now).

Would you mind reviewing and make sure I've understood correctly.

**Comment by wattanx** [comment]
No worries!

Your fixes have solved the problem I was hoping to solve!
Thank you so much ❤️

**Review by harlan-zw — APPROVED** [review]

**Pull request merged**
